[X86] Fix a warning
This patch fixes:

  llvm/lib/Target/X86/X86ISelLowering.cpp:31886:11: error: unused
  variable 'M' [-Werror,-Wunused-variable]

(cherry picked from commit f83eeacc9d344eaac117fe55c4d084954216d5ba)